# base:
#   S_size: 4
#   T: 5
#   coefficients: 
#     - 0
#     - 1
#     - -1
#   exp_dir: "exp"
#   exp_name: "debug"
#   device: "cuda"

trainer:
  T: 3
  S_size: 4
  coefficients: 
    - 0
    - 1
    - -1  
  exp_dir: "exp"
  exp_name: "S4T7_selfplay"
  device: "cuda:0"  
  self_play_device: "cuda:1"
  lr: 0.0001
  weight_decay: 0.00001
  gamma: .1
  step_size: 256
  iters_n: 12500
  batch_size: 16
  a_weight: .1
  v_weight: .9
  save_freq: 1250
  temp_save_freq: 625
  self_play_buffer: 1250
  self_play_freq: 10
  grad_clip: 4.0
  val_freq: 250

net:
  T: 3
  S_size: 4
  coefficients: 
    - 0
    - 1
    - -1
  device: 'cuda:0'

  N_steps: 3
  N_samples: 32
  n_attentive: 6
  N_heads: 8
  N_features: 32
  channel: 3
  scalar_size: 3
  policy_layers: 2
  value_layers: 3
  inter_channel: 512
  out_channel: 8

mcts:
  simulate_times: 20
  R_limit: 8

env:
  R_limit: 8
  T: 7
  S_size: 4
